export default {
    CHANGE_LOCATION: "CHANGE_LOCATION",
    SET_DATA: "SET_DATA",
    SET_DATES: "SET_DATES",
    SET_TEMPS: "SET_TEMPS",
    SET_SELECTED_DATE: "SET_SELECTED_DATE",
    SET_SELECTED_TEMP: "SET_SELECTED_TEMP"
}